language: go

go:
  - "1.10.x"

before_install:
  - go get -v github.com/hbahadorzadeh/wit

script:
  - go test
  - go build

before_deploy:
  - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "Hamed Bahadorzadeh"
  - git config --local user.email "Hamed Bahadorzadeh <h.bahadorzadeh@gmail.com>"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
  api_key:  $GITHUB_TOKEN
  file_glob: true
  file:
    - wit
  on:
    branch: master
    repo: hbahadorzadeh/wit

notifications:
  email:
    on_success: never
    on_failure: always
